package dx.cwl

import dx.cwl.Utils.{translateOptional, translateOptionalArray}
import org.w3id.cwl.cwl1_2.{CWLVersion, LoadListingEnum, SecondaryFileSchemaImpl}

import java.net.URI
import java.nio.file.Path

/**
  * An identifier of the form [\[namespace]#][frag], where frag is a
  * '/'-delimited string. For frag "foo/bar/baz", parent="foo/bar"
  * and name="baz".
  */
case class Identifier(namespace: Option[String], frag: Option[String]) {
  def fullyQualifiedName: Option[String] = {
    frag.map(n => namespace.map(ns => s"${ns}#${n}").getOrElse(n))
  }

  def parent: Option[String] = {
    frag.flatMap {
      case n if n.contains('/') => Some(n.substring(0, n.lastIndexOf('/')))
      case _                    => None
    }
  }

  def name: Option[String] = {
    frag.map {
      case n if n.contains('/') => n.substring(n.lastIndexOf('/') + 1)
      case n                    => n
    }
  }
}

object Identifier {

  def fromUri(uri: URI): Identifier = {
    val (namespace, name) = Utils.normalizeAndSplitUri(uri)
    Identifier(namespace, name)
  }

  def parse(uri: String,
            stripFragPrefix: Option[String] = None,
            defaultNamespace: Option[String] = None): Identifier = {
    val (namespace, frag) = (try {
      Utils.normalizeAndSplitUri(URI.create(uri))
    } catch {
      case _: IllegalArgumentException if uri.startsWith("_:") =>
        // this is a random id generated by the Java parser for an
        // anonymous/inline process
        (defaultNamespace, Some(uri.drop(2)))
      case _: Throwable => Utils.splitUri(uri)
    }) match {
      case (None, frag)      => (defaultNamespace, frag)
      case (namespace, frag) => (namespace, frag)
    }
    val strippedFrag = stripFragPrefix
      .map { s =>
        assert(s.endsWith("/"))
        frag.map {
          case p if p.startsWith(s) => p.drop(s.length)
          case p =>
            throw new Exception(s"frag ${p} does not start with prefix ${s}")
        }
      }
      .getOrElse(frag)
    Identifier(namespace, strippedFrag)
  }

  def get(id: java.util.Optional[String],
          defaultNamespace: Option[String],
          defaultFrag: Option[String] = None,
          source: Option[Path] = None,
          stripFragPrefix: Option[String] = None): Option[Identifier] = {
    translateOptional(id).map(Identifier.parse(_, stripFragPrefix, defaultNamespace)) match {
      case Some(id) if id.frag.isDefined => Some(id)
      case id if defaultFrag.isDefined =>
        id.map(_.copy(frag = defaultFrag))
          .orElse(Some(Identifier(namespace = None, frag = defaultFrag)))
      case id if source.isDefined =>
        val name = Some(source.get.getFileName.toString.dropRight(4))
        id.map(_.copy(frag = name)).orElse(Some(Identifier(namespace = None, frag = name)))
      case _ => None
    }
  }
}

object Document {
  type Document = Map[Identifier, Process]
  val empty: Document = Map.empty[Identifier, Process]

  implicit class DocumentAdder(doc: Document) {
    def addProcess(proc: Process): Document = {
      val id = proc.id
        .getOrElse(
            throw new Exception(s"process ${proc} has no ID")
        )
      if (doc.contains(id)) {
        throw new Exception(s"two processes have the same ID ${id}")
      }
      doc + (id -> proc)
    }
  }
}

trait Identifiable {
  val id: Option[Identifier]

  def getName: Option[String] = id.flatMap(_.frag)

  def hasName: Boolean = getName.isDefined

  def frag: String = id.flatMap(_.frag).getOrElse(throw new Exception(s"${this} has no name"))

  def parent: Option[String] = {
    if (hasName) {
      id.flatMap(_.parent)
    } else {
      throw new Exception(s"${this} has no name")
    }
  }

  def name: String =
    id.flatMap(_.name).getOrElse(throw new Exception(s"${this} has no name"))
}

trait Meta extends Identifiable {
  val label: Option[String]
  val doc: Option[String]
}

trait Loadable {
  val loadContents: Option[Boolean]
  val loadListing: Option[LoadListing.LoadListing]
}

trait Parameter extends Meta {
  val cwlType: CwlType
  val secondaryFiles: Vector[SecondaryFile]
  val streamable: Option[Boolean]
}

trait InputParameter extends Parameter with Loadable {
  val default: Option[CwlValue]
  val format: Vector[CwlValue]
}

trait OutputParameter extends Parameter {
  val format: Option[CwlValue]
}

/**
  * Marker trait for top-level elements (CommandLineTool, Workflow, ExpressionTool, etc)
  */
trait Process extends Meta {
  val source: Option[String]
  val cwlVersion: Option[CWLVersion]
  val label: Option[String]
  val doc: Option[String]
  val intent: Vector[String]
  val inputs: Vector[InputParameter]
  val outputs: Vector[OutputParameter]
  val requirements: Vector[Requirement]
  val hints: Vector[Hint]
}

// https://www.commonwl.org/v1.2/CommandLineTool.html#SecondaryFileSchema
case class SecondaryFile(pattern: CwlValue, required: CwlValue)

object SecondaryFile {
  def apply(secondaryFile: SecondaryFileSchemaImpl,
            schemaDefs: Map[String, CwlSchema]): SecondaryFile = {
    SecondaryFile(CwlValue(secondaryFile.getPattern, schemaDefs),
                  CwlValue(secondaryFile.getRequired, schemaDefs))
  }

  def applyArray(secondaryFiles: java.lang.Object,
                 schemaDefs: Map[String, CwlSchema]): Vector[SecondaryFile] = {
    translateOptionalArray(secondaryFiles).map {
      case sf: SecondaryFileSchemaImpl => SecondaryFile(sf, schemaDefs)
      case other =>
        throw new RuntimeException(s"unexpected SecondaryFile value ${other}")
    }
  }
}

// https://www.commonwl.org/v1.2/CommandLineTool.html#LoadListingEnum
object LoadListing extends Enumeration {
  type LoadListing = Value
  val No, Shallow, Deep = Value

  def from(loadListing: LoadListingEnum): LoadListing = {
    loadListing match {
      case LoadListingEnum.NO_LISTING      => No
      case LoadListingEnum.SHALLOW_LISTING => Shallow
      case LoadListingEnum.DEEP_LISTING    => Deep
    }
  }
}
