name : Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: |
          sudo apt-get update
          # compile antlr4 sources
          cd ${GITHUB_WORKSPACE}
          make
      - name: Unit Tests
        run: |
          sbt test
      - name: Scala formatting
        run: |
          sbt scalafmtCheckAll
