name: Main Workflow
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
permissions:
  contents: read
  packages: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - name: Install Java
        uses: actions/setup-java@d202f5dbf7256730fb690ec59f6381650114feb2 # v1.4.3
        with:
          java-version: 11
      - name: Build
        run: |
          # compile antlr4 sources
          cd ${GITHUB_WORKSPACE}
          make
      - name: Compile & Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt scalafmtCheckAll
          sbt test

